select A.DATAAREAID,A.PRODID,  A.BOMDATE,B.SUP_BOMDATE from PRODTABLE A

join SALESLINE B on  b.DATAAREAID=A.DATAAREAID and B.INVENTTRANSID=A.TEC_SALESINVENTTRANSID 

where B.SUP_BOMDATE='2018-4-1'

go

select A.DATAAREAID ,A.SALESID,A.INVENTTRANSID,
inter.dataareaid,Inter.INVENTTRANSID,
A.SUP_BOMDATE,inter.SUP_BOMDATE  as InterBOMdate,
prod.PRODID,prod.DATAAREAID, 
prod.BOMDATE    from SALESLINE  A


left join PURCHLINE B  on  B.DATAAREAID=A.DATAAREAID and B.INVENTREFTRANSID=A.INVENTTRANSID
left join PURCHTABLE C on  C.DATAAREAID=A.DATAAREAID and C.PURCHID=b.PURCHID
left join SALESLINE inter on inter.DATAAREAID=C.INTERCOMPANYCOMPANYID and inter.INVENTTRANSID=B.INTERCOMPANYINVENTTRANSID
left join PRODTABLE prod  on prod.DATAAREAID=inter.DATAAREAID and prod.TEC_SALESINVENTTRANSID=inter.INVENTTRANSID
where A.DATAAREAID='001' and A.SUP_BOMDATE='2018-4-1'  and 