select A.DATAAREAID ,A.PURCHID,A.CREATEDDATETIME from PURCHTABLE A where 

A.DATAAREAID in ('001','005','301','501','201','002')

--and A.ITEMBUYERGROUPID='Purdep'
and A.CREATEDDATETIME<GETDATE()-2
and not exists  
(select 1 from PURCHLINE B where B.DATAAREAID=A.DATAAREAID and B.PURCHID=A.PURCHID)

order by A.CREATEDDATETIME desc 

go

delete PURCHTABLE  where 

PURCHTABLE.DATAAREAID in ('001','005','301','501','201','002')

--and PURCHTABLE.ITEMBUYERGROUPID='Purdep'
and PURCHTABLE.CREATEDDATETIME<GETDATE()-2
and not exists  
(select 1 from PURCHLINE B where B.DATAAREAID=PURCHTABLE.DATAAREAID and B.PURCHID=PURCHTABLE.PURCHID)