select 
prod.DATAAREAID,
prod.CONFIRMEDDLV,
prod.PRODID,
prod.PRODSTATUS,
prod.WORKSHOP,
prod.PRODUCTLINE,
prod.ITEMID,
dim.CONFIGID,
config.NAME,
prod.QTYSCHED,
prod.BOMID,
prod.BOMDATE,

pbom.ITEMID as MMItem,
it.ITEMNAME,
it.NAMEALIAS,
it.ITEMGROUPID,
dbom.INVENTCOLORID,
color.NAME,
pbom.GROUPID,
pbom.BOMQTYSERIE,
pbom.BOMQTY,
pbom.SCRAPVAR,
pbom.UNITID,
pbom.QTYBOMCALC,
pbom.REMAINBOMFINANCIAL,
pbom.ACTURALPICKQTY,
pbom.BOMRefRecId,
pbom.BOMID,
bom.BOMID,
bom.FROMDATE,
bom.TODATE,
bom.BOMQTY,
bom.SCRAPVAR,
bom.UNITID,
bom.BOMQTYSERIE

from  PRODTABLE prod 

join INVENTDIM dim on dim.DATAAREAID=prod.DATAAREAID and dim.INVENTDIMID=prod.INVENTDIMID
join CONFIGTABLE config on config.DATAAREAID=prod.DATAAREAID and config.ITEMID=prod.ITEMID and config.CONFIGID=dim.CONFIGID
join PRODBOM	 pbom on pbom.DATAAREAID=prod.DATAAREAID and pbom.PRODID=prod.PRODID
join INVENTDIM   dbom on dbom.DATAAREAID=pbom.DATAAREAID and dbom.INVENTDIMID=pbom.INVENTDIMID
join INVENTTABLE  it on it.DATAAREAID=pbom.DATAAREAID and it.ITEMID=pbom.ITEMID and it.ITEMGROUPID=N'Lthr¥Ö®Æ'
join INVENTCOLOR color on color.DATAAREAID=dbom.DATAAREAID and color.ITEMID=pbom.ITEMID and color.INVENTCOLORID=dbom.INVENTCOLORID
join BOM   bom on bom.DATAAREAID=pbom.DATAAREAID and bom.RECID=pbom.BOMREFRECID
where prod.DATAAREAID in ('001','201','301','321','501','601','611')
and (prod.CONFIRMEDDLV>='2018-01-01' and prod.CONFIRMEDDLV<='2018-3-31')
and prod.PRODSTATUS in (5,7)

union 

select 
prod.DATAAREAID,
prod.CONFIRMEDDLV,
prod.PRODID,
prod.PRODSTATUS,
prod.WORKSHOP,
prod.PRODUCTLINE,
prod.ITEMID,
dim.CONFIGID,
config.NAME,
prod.QTYSCHED,
prod.BOMID,
prod.BOMDATE,

pbom.ITEMID as MMItem,
it.ITEMNAME,
it.NAMEALIAS,
it.ITEMGROUPID,
dbom.INVENTCOLORID,
color.NAME,
pbom.GROUPID,
pbom.BOMQTYSERIE,
pbom.BOMQTY,
pbom.SCRAPVAR,
pbom.UNITID,
pbom.QTYBOMCALC,
pbom.REMAINBOMFINANCIAL,
pbom.ACTURALPICKQTY,
pbom.BOMRefRecId,
pbom.BOMID,
bom.BOMID,
bom.FROMDATE,
bom.TODATE,
bom.BOMQTY,
bom.SCRAPVAR,
bom.UNITID,
bom.BOMQTYSERIE

from  PRODTABLE prod 

join INVENTDIM dim on dim.DATAAREAID=prod.DATAAREAID and dim.INVENTDIMID=prod.INVENTDIMID
join CONFIGTABLE config on config.DATAAREAID=prod.DATAAREAID and config.ITEMID=prod.ITEMID and config.CONFIGID=dim.CONFIGID
join PRODBOM	 pbom on pbom.DATAAREAID=prod.DATAAREAID and pbom.PRODID=prod.PRODID
join INVENTDIM   dbom on dbom.DATAAREAID=pbom.DATAAREAID and dbom.INVENTDIMID=pbom.INVENTDIMID
join INVENTTABLE  it on it.DATAAREAID=pbom.DATAAREAID and it.ITEMID=pbom.ITEMID and it.ITEMGROUPID=N'Lthr¥Ö®Æ'
join INVENTCOLOR color on color.DATAAREAID=dbom.DATAAREAID and color.ITEMID=pbom.ITEMID and color.INVENTCOLORID=dbom.INVENTCOLORID
left join BOM   bom on bom.DATAAREAID=pbom.DATAAREAID and bom.RECID=pbom.BOMREFRECID
where prod.DATAAREAID in ('001','201','301','321','501','601','611')
and (prod.CONFIRMEDDLV>='2018-01-01' and prod.CONFIRMEDDLV<='2018-3-31')
and prod.PRODSTATUS in (5,7) and bom.BOMID is null 


