select 
A.DATAAREAID,
B.VENDACCOUNT,
B.PURCHID,
B.ITEMID,
c.ITEMNAME,
Dim.INVENTCOLORID,
color.NAME,
B.PURCHQTY,
B.PURCHUNIT,
B.INVENTTRANSID ,
A.CUSTACCOUNT,
A.SALESID as SOSalesId,
A.ITEMID as SOItemId,
A.INVENTTRANSID as SOInventTransId,
convert(date,dateadd(HH,8,A.CREATEDDATETIME)) as SOCreateDateTime,
convert(date,A.CREATEDDATE) as SOCreatedate,
convert(date,DATEADD(HH,8,B.CREATEDDATETIME)) as POCreateDateTime

from SALESLINE A

join PURCHLINE B on B.DATAAREAID=A.DATAAREAID and B.TEC_SALESINVENTTRANSID=A.INVENTTRANSID
join INVENTDIM dim on dim.DATAAREAID=A.DATAAREAID and dim.INVENTDIMID =B.INVENTDIMID
join INVENTTABLE c on C.DATAAREAID=B.DATAAREAID  and  C.ITEMID=B.ITEMID

join INVENTCOLOR color on color.DATAAREAID=dim.DATAAREAID and color.INVENTCOLORID=dim.INVENTCOLORID and color.ITEMID=b.ITEMID


where A.DATAAREAID in ('001','301','321','501','601','611')
and B.itemId like 'H%'
and A.CUSTACCOUNT in ('CH','MK','SH-MK','SH-CH')
and dateadd(HH,8,A.CREATEDDATETIME)>='2017-7-1' and dateadd(HH,8,A.CREATEDDATETIME)<='2017-12-31'