select 
A.DATAAREAID, 
A.PurchId, 
MIN(A.CREATEDDATETIME) as CREATEDDATE,
A.ItemId,
A.TEC_LEAVEFACTORYDATE,
B.InventColorId,
B.InventSizeId,
B.configId,
MIN(A.VENDACCOUNT)     as VendAccount,
MAX(A.[SUP_YearMonth]) as YM,
max([ItemBuyerGroupId]) as ItemBuyerGroupId,
max([SUP_INTERCOMPANYPURCHITEMID]) as SUP_INTERCOMPANYPURCHITEMID,
max(A.SUP_REFERENCE)  as SUP_REFERENCE,
max(A.PURCHUNIT) as PURCHUNIT,
MAX(A.DELIVERYDATE) as DELIVERYDATE,
MAX(A.SUP_RequireDelivery) as SUP_RequireDelivery,
MAX(A.TEC_FIRSTCONFIRMATIONDATE) as TEC_FIRSTCONFIRMATIONDATE,
MAX(A.CONFIRMEDDLV) as CONFIRMEDDLV,
MAX(A.MODIFIEDDATETIME) as MODIFIEDDATETIME,
MAX(salesid)       as SalesId,
MAX(A.custAccount) as  CUSTACCOUNT,
MAX(A.ETDDATE) as ETDDate,
MAX(A.TEC_ARRIVALDATE) as TEC_ARRIVALDATE, 
SUM(A.purchqty) as PurchQty,
SUM(A.QM_INSPQTYPURCH-A.THK_SHORTAGEQTY) as ReceiveNowIQC,
SUM(REMAINPURCHPHYSICAL) as REMAINPURCHPHYSICAL,
SUM(A.REMAINPURCHFINANCIAL) as RemainInvoice,
SUM(A.THK_SHORTAGEQTY) as OweQty

--SUM(RemianPurchQytQM) as RemianPurchQytQM
from PURCHLINE A

join INVENTDIM  B on B.DATAAREAID=A.DATAAREAID and B.INVENTDIMID=A.INVENTDIMID



where exists( select 1 from PURCHLINE find where find.DATAAREAID=A.DATAAREAID and find.PURCHID=A.PURCHID and find.REMAININVENTPHYSICAL!=0)
and A.DATAAREAID='001'
--A.DATAAREAID='001'
and A.PURCHID='A1-201801/00015'
--and A.CREATEDDATETIME>='2017-6-30'
 
group by A.DATAAREAID, A.PurchId, A.ItemId,
A.TEC_LEAVEFACTORYDATE,
B.InventColorId,B.InventSizeId,B.configId