select * from 

(select 
A.DATAAREAID,
substring(A.PURCHID,4,6) as YM1 ,
replace(CONVERT(varchar(7),A.CREATEDDATETIME,120),'-','') as YM,
--DATEPART(YEAR,A.CREATEDDATETIME) as YEAR,
--DATEPART(MONTH,A.CREATEDDATETIME) as MONTH,
A.PURCHID,A.CREATEDDATETIME from PURCHTABLE A   

where substring(A.PURCHID,4,6)<>replace(CONVERT(varchar(7),A.CREATEDDATETIME,120),'-','') 

and A.INTERCOMPANYSALESID='' 
--order by A.CREATEDDATETIME desc 

union 

select 
A.DATAAREAID,
substring(A.PURCHID,4,6) as YM1,
replace(CONVERT(varchar(7),A.CREATEDDATETIME,120),'-','') as YM,
--DATEPART(YEAR,A.CREATEDDATETIME) as YEAR,
--DATEPART(MONTH,A.CREATEDDATETIME) as MONTH,
A.PURCHID,A.CREATEDDATETIME from PURCHTABLE A   

where substring(A.PURCHID,4,6)<>replace(CONVERT(varchar(7),A.CREATEDDATETIME,120),'-','') 

and A.INTERCOMPANYDIRECTDELIVERY=0 ) as MM

where MM.DATAAREAID not in ('101','ut1','202','uat')
order by MM.CREATEDDATETIME  desc 
--order by A.CREATEDDATETIME desc 

go

select A.DATAAREAID,A.PURCHID,A.CREATEDDATETIME from PURCHTABLE A

where A.PURCHID like '%201801%' or A.PURCHID like '%201802%'