select 
A.DATAAREAID,
A.VENDACCOUNT,
B.PURCHNAME,
B.SUP_VENDNUM,
A.PURCHID,
A.SUP_PICKER,
A.SUP_PURCHREQDEPARTMENT,
A.SUP_REFERENCE,
A.ITEMID,
it.ITEMNAME,
a.PURCHPRICE,
A.PURCHQTY,
A.CURRENCYCODE,
A.LINEAMOUNT,
A.LINEAMOUNTMST,
A.PURCHPLACER,
A.ITEMBUYERGROUPID,
c.INVENTCOLORID,
c.INVENTSITEID,
c.INVENTLOCATIONID,
A.PURCHUNIT,
purchreq.OAID,
A.PURCHREQID,
A.SUP_APPROVEDATE,
DATEADD(HH,8,A.CREATEDDATETIME)  as CreateDate


from PURCHLINE A

join PURCHTABLE B on B.DATAAREAID=A.DATAAREAID and B.PURCHID=A.PURCHID

join INVENTDIM  C on C.DATAAREAID=A.DATAAREAID and C.INVENTDIMID=A.INVENTDIMID

join INVENTTABLE it on it.DATAAREAID=A.DATAAREAID and it.ITEMID=A.ITEMID

left join PURCHREQTABLE  purchreq on purchreq.DATAAREAID=a.DATAAREAID and purchreq.PURCHREQID=A.PURCHREQID

where A.DATAAREAID in ('002','203')

and (A.SUP_PURCHREASON like N'%工程%'
or A.SUP_PURCHREASON like N'%外判维修%'
or A.SUP_PURCHREASON like N'%厂房和设施维护%')

union 

select 
A.DATAAREAID,
A.VENDACCOUNT,
B.PURCHNAME,
B.SUP_VENDNUM,
A.PURCHID,
A.SUP_PICKER,
A.SUP_PURCHREQDEPARTMENT,
A.SUP_REFERENCE,
A.ITEMID,
it.ITEMNAME,
a.PURCHPRICE,
A.PURCHQTY,
A.CURRENCYCODE,
A.LINEAMOUNT,
A.LINEAMOUNTMST,
A.PURCHPLACER,
A.ITEMBUYERGROUPID,
c.INVENTCOLORID,
c.INVENTSITEID,
c.INVENTLOCATIONID,
A.PURCHUNIT,
purchreq.OAID,
A.PURCHREQID,
A.SUP_APPROVEDATE,
DATEADD(HH,8,A.CREATEDDATETIME)  as CreateDate


from PURCHLINE A

join PURCHTABLE B on B.DATAAREAID=A.DATAAREAID and B.PURCHID=A.PURCHID

join INVENTDIM  C on C.DATAAREAID=A.DATAAREAID and C.INVENTDIMID=A.INVENTDIMID

join INVENTTABLE it on it.DATAAREAID=A.DATAAREAID and it.ITEMID=A.ITEMID

left join PURCHREQTABLE  purchreq on purchreq.DATAAREAID=a.DATAAREAID and purchreq.PURCHREQID=A.PURCHREQID

where A.DATAAREAID in ('002','203')

and A.ITEMID like N'%工程%'

union 

select 
A.DATAAREAID,
A.VENDACCOUNT,
B.PURCHNAME,
B.SUP_VENDNUM,
A.PURCHID,
A.SUP_PICKER,
A.SUP_PURCHREQDEPARTMENT,
A.SUP_REFERENCE,
A.ITEMID,
it.ITEMNAME,
a.PURCHPRICE,
A.PURCHQTY,
A.CURRENCYCODE,
A.LINEAMOUNT,
A.LINEAMOUNTMST,
A.PURCHPLACER,
A.ITEMBUYERGROUPID,
c.INVENTCOLORID,
c.INVENTSITEID,
c.INVENTLOCATIONID,
A.PURCHUNIT,
purchreq.OAID,
A.PURCHREQID,
A.SUP_APPROVEDATE,
DATEADD(HH,8,A.CREATEDDATETIME)  as CreateDate


from PURCHLINE A

join PURCHTABLE B on B.DATAAREAID=A.DATAAREAID and B.PURCHID=A.PURCHID

join INVENTDIM  C on C.DATAAREAID=A.DATAAREAID and C.INVENTDIMID=A.INVENTDIMID

join INVENTTABLE it on it.DATAAREAID=A.DATAAREAID and it.ITEMID=A.ITEMID

left join PURCHREQTABLE  purchreq on purchreq.DATAAREAID=a.DATAAREAID and purchreq.PURCHREQID=A.PURCHREQID

where A.DATAAREAID in ('002','203')

and A.SUP_REFERENCE like N'%工程%'

