select A.DATAAREAID,A.PRODID,  A.BOMDATE,B.SUP_BOMDATE from PRODTABLE A

join SALESLINE B on  b.DATAAREAID=A.DATAAREAID and B.INVENTTRANSID=A.TEC_SALESINVENTTRANSID 

where B.SUP_BOMDATE='2018-4-1' and B.DATAAREAID in ('321','611')

go

update PRODTABLE set BOMDATE=B.SUP_BOMDATE

from  PRODTABLE A

join SALESLINE B on  b.DATAAREAID=A.DATAAREAID and B.INVENTTRANSID=A.TEC_SALESINVENTTRANSID 

where B.SUP_BOMDATE='2018-4-1' and B.DATAAREAID in ('321','611')